version: 1.0.{build}
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
before_build:
  - cmd: java -version
  - cmd: wget http://www.motorlogy.com/apache/maven/maven-3/3.2.3/binaries/apache-maven-3.2.3-bin.zip
  - cmd: mvn -version
test_script:
  - cmd: mvn clean install -Pqulice

